version: '1'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:4200
    networks:
      - app-network

  backend:
    image: sliu9303/express_backend
    ports:
      - 3030:3000
    networks:
      - app-network
networks:
  app-network:
    driver: bridge