version: '1'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 4200:80
    networks:
      - app-network

  backend:
    image: sliu9303/express_backend
    ports:
      - 4242:4242
    networks:
      - app-network
networks:
  app-network:
    driver: bridge